image: "haskell:8.6.5"

before_script:
  - locale
  - stack --version

variables:
  LANG: "C.UTF-8"
  LC_ALL: "C.UTF-8"
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

stages:
  - haskell_build
  - site_build
  - test
  - deploy

build_haskell:
  stage: haskell_build
  tags: 
    - docker
  before_script:
    - locale
    - stack --version
    - stack setup --system-ghc
    - stack install --system-ghc --only-dependencies
  script:
    - stack build --system-ghc
    - du -hcs .stack-work/ .stack-root/
  artifacts:
    paths:
      - .stack-work/

build_site:
  stage: site_build
  tags:
    - docker
  needs:
    - job: "build_haskell"
      artifacts: true
  artifacts:
    paths:
      - _cache/
      - _site/
  script:
    - stack exec --system-ghc site build

check_links:
    stage: test
    tags:
      - docker
    needs:
      - job: "build_haskell"
        artifacts: true
      - job: "build_site"
        artifacts: true
    script:
      - stack exec --system-ghc site check

.deploy:
  stage: deploy
  tags:
    - docker
  needs:
    - job: "build_site"
      artifacts: true
  script:
    - mkdir .public
    - cp -r _site/* .public
    - mv .public public
  artifacts:
    paths:
      - public

create_archive:
  extends: .deploy
  except:
    - master

pages:
  extends: .deploy
  only:
      - master
